# fly.toml app configuration file generated for resume-builder-app-misty-waterfall-5852 on 2026-01-18T18:12:17+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'resume-builder-app-misty-waterfall-5852'
primary_region = 'iad'

[swap]
  size_mb = 512
  max_swap_in_mb = 512

[env]
  JAVA_OPTS = '-Xms128m -Xmx256m -XX:+UseSerialGC'
  PORT = '8080'
  SPRING_PROFILES_ACTIVE = 'prod'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '30s'
    timeout = '15s'
    grace_period = '3m0s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
